version: 2

defaults: &defaults
  working_directory: /go/src/github.com/deciphernow/releaser
  docker:
    - image: golang:1.16

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: apt-get update && apt-get install -y ca-certificates git 
      - run: CGO_ENABLED=0 go build
      - run: 
          name: Release
          command: | 
            export $(cat VERSION | grep VERSION)
            ./releaser github --token $GITHUB_TOKEN --semver $VERSION --organization deciphernow --asset releaser,CHANGELOG.md,README.md
      
workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master